# -*- coding: utf-8 -*-
"""01_image_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vliiAXBH87p6acclIoiRWOeHBVByataE

##Data cleaning
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = "/content/drive/MyDrive/Environmental_ai_healthcare_system/dataset"
RAW_PATH = os.path.join(BASE_PATH, "raw")
PROCESSED_PATH = os.path.join(BASE_PATH, "processed")

classes = os.listdir(RAW_PATH)

for cls in classes:
    os.makedirs(os.path.join(PROCESSED_PATH, cls), exist_ok=True)

from PIL import Image
from tqdm import tqdm

IMG_SIZE = 224

for cls in classes:
    input_folder = os.path.join(RAW_PATH, cls)
    output_folder = os.path.join(PROCESSED_PATH, cls)

    for img_name in tqdm(os.listdir(input_folder)):
        img_path = os.path.join(input_folder, img_name)

        try:
            with Image.open(img_path) as img:
                img = img.convert("RGB")
                img = img.resize((IMG_SIZE, IMG_SIZE))
                img.save(os.path.join(output_folder, img_name))

        except:
            print("Skipped corrupt image:", img_name)

import os

for cls in os.listdir(PROCESSED_PATH):
    class_path = os.path.join(PROCESSED_PATH, cls)
    print(cls, ":", len(os.listdir(class_path)))

"""##Data preprocessing

"""

!rm -rf /content/drive

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import random

BASE_PATH = "/content/drive/MyDrive/Environmental_ai_healthcare_system/dataset"
PROCESSED_PATH = os.path.join(BASE_PATH, "processed")

SPLIT_PATH = os.path.join(BASE_PATH, "split_v2")

TRAIN_PATH = os.path.join(SPLIT_PATH, "train")
VAL_PATH = os.path.join(SPLIT_PATH, "val")
TEST_PATH = os.path.join(SPLIT_PATH, "test")

# Create main directories
os.makedirs(TRAIN_PATH, exist_ok=True)
os.makedirs(VAL_PATH, exist_ok=True)
os.makedirs(TEST_PATH, exist_ok=True)

classes = os.listdir(PROCESSED_PATH)

for cls in classes:
    class_folder = os.path.join(PROCESSED_PATH, cls)
    images = os.listdir(class_folder)

    random.shuffle(images)

    total = len(images)
    train_split = int(0.8 * total)
    val_split = int(0.9 * total)

    train_images = images[:train_split]
    val_images = images[train_split:val_split]
    test_images = images[val_split:]

    # Create class subfolders
    os.makedirs(os.path.join(TRAIN_PATH, cls), exist_ok=True)
    os.makedirs(os.path.join(VAL_PATH, cls), exist_ok=True)
    os.makedirs(os.path.join(TEST_PATH, cls), exist_ok=True)

    # Copy images
    for img in train_images:
        shutil.copy(
            os.path.join(class_folder, img),
            os.path.join(TRAIN_PATH, cls, img)
        )

    for img in val_images:
        shutil.copy(
            os.path.join(class_folder, img),
            os.path.join(VAL_PATH, cls, img)
        )

    for img in test_images:
        shutil.copy(
            os.path.join(class_folder, img),
            os.path.join(TEST_PATH, cls, img)
        )

print("80-10-10 Train-Val-Test Split (split_v2) Completed Successfully!")

print("Train folders:", os.listdir(TRAIN_PATH))
print("Test folders:", os.listdir(TEST_PATH))
print("Validation folders:", os.listdir(VAL_PATH))

for cls in os.listdir(TRAIN_PATH):
    print("TRAIN", cls, ":", len(os.listdir(os.path.join(TRAIN_PATH, cls))))

for cls in os.listdir(TEST_PATH):
    print("TEST", cls, ":", len(os.listdir(os.path.join(TEST_PATH, cls))))

for cls in os.listdir(VAL_PATH):
    print("VAL", cls, ":", len(os.listdir(os.path.join(VAL_PATH, cls))))