# -*- coding: utf-8 -*-
"""02_transfer_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mtYc3azx3vqb_zNYcs7MiU7SOicedpz
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Model Training

## MobileNetV2
"""

!cp -r "/content/drive/MyDrive/Environmental_ai_healthcare_system/dataset/split_v2" /content/

import os

print(os.listdir("/content"))
print(os.listdir("/content/split_v2"))
print(os.listdir("/content/split_v2/train"))

BASE_PATH = "/content/split_v2"

TRAIN_PATH = os.path.join(BASE_PATH, "train")
TEST_PATH = os.path.join(BASE_PATH, "test")
VAL_PATH = os.path.join(BASE_PATH, "val")

import random
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense
from tensorflow.keras.applications import MobileNetV2

from sklearn.utils import class_weight
from sklearn.metrics import confusion_matrix, classification_report

IMG_SIZE = 224
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    TRAIN_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    VAL_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    TEST_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Classes:", class_names)

normalization_layer = tf.keras.layers.Rescaling(1./255)

train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y)).prefetch(AUTOTUNE)
val_ds = val_ds.map(lambda x, y: (normalization_layer(x), y)).prefetch(AUTOTUNE)
test_ds = test_ds.map(lambda x, y: (normalization_layer(x), y)).prefetch(AUTOTUNE)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
])

print("Collecting training labels for class weight calculation...")
train_labels = []

for _, labels in train_ds.unbatch():
    train_labels.append(labels.numpy())

train_labels = np.array(train_labels)

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels),
    y=train_labels
)

class_weights_dict = dict(enumerate(class_weights))

print("Class weights calculated:")
for i, weight in class_weights_dict.items():
    print(f"  Class {class_names[i]} ({i}): {weight:.2f}")

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    min_delta=0.001,
    restore_best_weights=True,
    verbose=1
)

base_model_mob = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base_model_mob.trainable = False

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = base_model_mob(x, training=False)
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation="relu")(x)
outputs = Dense(num_classes, activation="softmax")(x)

model_mob = Model(inputs, outputs)

model_mob.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model_mob.summary()

print("Training model with data augmentation...")
history_mob = model_mob.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weights_dict,
    callbacks=[early_stop]
)

# Fine-tuning
base_model_mob.trainable = True

for layer in base_model_mob.layers[:-60]:
    layer.trainable = False

model_mob.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Fine-tuning model with data augmentation...")
history_finetune_mob = model_mob.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weights_dict,
    callbacks=[early_stop]
)

test_ds_eval = tf.keras.preprocessing.image_dataset_from_directory(
    TEST_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=False
)
test_ds_eval = test_ds_eval.map(lambda x, y: (normalization_layer(x), y))
test_ds_eval = test_ds_eval.prefetch(buffer_size=AUTOTUNE)

y_pred_probs_mob = model_mob.predict(test_ds_eval)
y_pred_mob = np.argmax(y_pred_probs_mob, axis=1)

y_true_mob = np.concatenate([y for x, y in test_ds_eval], axis=0)

cm_mob = confusion_matrix(y_true_mob, y_pred_mob)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
plt.imshow(cm_mob, interpolation='nearest', cmap=plt.cm.Blues)
plt.title("Confusion Matrix (MobileNetV2)")
plt.colorbar()

tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45, ha="right")
plt.yticks(tick_marks, class_names)

fmt = 'd'
thresh = cm_mob.max() / 2.
for i in range(cm_mob.shape[0]):
    for j in range(cm_mob.shape[1]):
        plt.text(j, i, format(cm_mob[i, j], fmt),
                 ha="center", va="center",
                 color="white" if cm_mob[i, j] > thresh else "black")

plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.tight_layout()
plt.show()

# Classification Report
print("Classification Report (MobileNetV2):")
print(classification_report(y_true_mob, y_pred_mob, target_names=class_names))

# Plotting training and validation accuracy for fine-tuning
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(history_finetune_mob.history['accuracy'], label='Training Accuracy')
plt.plot(history_finetune_mob.history['val_accuracy'], label='Validation Accuracy')
plt.title('Fine-tuning Training and Validation Accuracy (MobileNetV2)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plotting training and validation loss for fine-tuning
plt.subplot(1, 2, 2)
plt.plot(history_finetune_mob.history['loss'], label='Training Loss')
plt.plot(history_finetune_mob.history['val_loss'], label='Validation Loss')
plt.title('Fine-tuning Training and Validation Loss (MobileNetV2)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

model_mob.save("/content/drive/MyDrive/Environmental_ai_healthcare_system/mobilenet_model.keras")

"""## EfficientNetB0"""

IMG_SIZE = 224
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    TRAIN_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    VAL_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    TEST_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Classes:", class_names)

from tensorflow.keras.applications.efficientnet import preprocess_input

train_ds = train_ds.map(lambda x, y: (preprocess_input(x), y)).prefetch(AUTOTUNE)
val_ds = val_ds.map(lambda x, y: (preprocess_input(x), y)).prefetch(AUTOTUNE)
test_ds = test_ds.map(lambda x, y: (preprocess_input(x), y)).prefetch(AUTOTUNE)

from tensorflow.keras.applications import EfficientNetB0

base_model_eff = EfficientNetB0(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model_eff.trainable = False

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = base_model_eff(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dense(128, activation="relu")(x)
outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)

model_eff = tf.keras.Model(inputs, outputs)

model_eff.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model_eff.summary()

history_eff = model_eff.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    class_weight=class_weights_dict,
    callbacks=[early_stop]
)

#Fine Tuning
base_model_eff.trainable = True

for layer in base_model_eff.layers[:-60]:
    layer.trainable = False

model_eff.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history_eff_finetune = model_eff.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weights_dict,
    callbacks=[early_stop]
)

from tensorflow.keras.applications.efficientnet import preprocess_input

test_ds_eval = tf.keras.preprocessing.image_dataset_from_directory(
    TEST_PATH,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_ds_eval = test_ds_eval.map(
    lambda x, y: (preprocess_input(x), y)
).prefetch(AUTOTUNE)

# Predictions
y_pred_probs_eff = model_eff.predict(test_ds_eval)
y_pred_eff = np.argmax(y_pred_probs_eff, axis=1)

# True labels
y_true_eff = np.concatenate(
    [y.numpy() for _, y in test_ds_eval],
    axis=0
)

# Confusion Matrix
cm_eff = confusion_matrix(y_true_eff, y_pred_eff)

# Plot
plt.figure(figsize=(8, 6))
plt.imshow(cm_eff, interpolation='nearest', cmap=plt.cm.Blues)
plt.title("Confusion Matrix (EfficientNetB0)")
plt.colorbar()

tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45, ha="right")
plt.yticks(tick_marks, class_names)

fmt = 'd'
thresh = cm_eff.max() / 2.
for i in range(cm_eff.shape[0]):
    for j in range(cm_eff.shape[1]):
        plt.text(j, i, format(cm_eff[i, j], fmt),
                 ha="center", va="center",
                 color="white" if cm_eff[i, j] > thresh else "black")

plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.tight_layout()
plt.show()

# Classification Report
print("Classification Report (EfficientNetB0):")
print(classification_report(y_true_eff, y_pred_eff, target_names=class_names))

# Plotting training and validation accuracy for EfficientNet fine-tuning
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.plot(history_eff_finetune.history['accuracy'], label='Training Accuracy')
plt.plot(history_eff_finetune.history['val_accuracy'], label='Validation Accuracy')
plt.title('Fine-tuning Training and Validation Accuracy (EfficientNetB0)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plotting training and validation loss for EfficientNet fine-tuning
plt.subplot(1, 2, 2)
plt.plot(history_eff_finetune.history['loss'], label='Training Loss')
plt.plot(history_eff_finetune.history['val_loss'], label='Validation Loss')
plt.title('Fine-tuning Training and Validation Loss (EfficientNetB0)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

model_eff.save("/content/drive/MyDrive/Environmental_ai_healthcare_system/efficientnet_model.keras")

"""### Final Model: **EfficientNetB0**

Chosen over MobileNetV2 due to improved minority class recall (97% vs 88% for garbage_dirty), ensuring better detection of critical environmental risk cases.

# Demo
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.models import load_model

model_eff = load_model("/content/drive/MyDrive/Environmental_ai_healthcare_system/efficientnet_model.keras")

from google.colab import files
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.models import load_model

# Upload file
uploaded = files.upload()

# Get filename
img_path = list(uploaded.keys())[0]

# Load and preprocess image
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

class_names = ['air_pollution', 'garbage_dirty', 'hygienic_environment', 'stagnant_water']

# Predict
predictions = model_eff.predict(img_array)
predicted_class = class_names[np.argmax(predictions[0])]
confidence = np.max(predictions[0]) * 100

# Display image
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediction: {predicted_class}\nConfidence: {confidence:.2f}%")
plt.show()